spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@197.200.11.77:1521/PROD
spring.datasource.username=CBOEA
spring.datasource.password=cboea
spring.datasource.platform=oracle
spring.datasource.initialization-mode=never

spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true
# NLS_LANG ??
spring.datasource.hikari.connection-init-sql=ALTER SESSION SET NLS_LANGUAGE=AMERICAN NLS_TERRITORY=AMERICA


#JPA Auditing ??
spring.jpa.properties.org.hibernate.envers.store_data_at_delete=true
spring.jpa.mapping-resources=META-INF/orm.xml
#JPA Auditing ??

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.max-file-size=100MB

# Linux
file.upload-dir=/data/apps/ije-eacct/uploads
file.decode-dir=/data/apps/ije-eacct/decoded
xmlFile.upload-dir=/data/apps/ije-eacct/xml
oldFile.upload-dir=/data/apps/oldFiles

server.port=19500
server.display-name=framework-api-server

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=never
spring.session.timeout.seconds=86400

server.servlet.context-parameters.RTSSO_SP_CONFIG=classpath:rathon_sso_sp_product.properties


opagent.app.ptk.use=N
opagent.sso.server.context=
opagent.sso.server.login.url=index.html
opagent.sso.server.logout.url=logout.html
opagent.sso.server.ip=197.200.11
opagent.sso.server.port=
opagent.cookieUse=Y
opagent.validate.request.timeout=5000
opagent.sso.client.login=N
opagent.login.view.emate.apps=APP_143
opagent.sso.server.url=http://wingsso.iljin.co.kr/
opagent.apps.login.url=http://{Back-end-Host}:{Port}/login/sso
opagent.apps.logout.url=http://{Back-end-Host}:{Port}/logout/sso

# logging
logging.level.iljin.framework=INFO
logging.file.path=./data/apps/ije-eacct/logs/api-logs
logging.level.org.springframework.jdbc.core = INFO
logging.level.org.springframework.web=INFO


#logging.level.org.hibernate.type=TRACE

spring.mail.host=197.200.11.57
spring.mail.port=25
server.domain-name=eleceas.iljin.co.kr

spring.boot.admin.client.url=http://localhost:12000
spring.boot.admin.client.username=admin
spring.boot.admin.client.password=admin
spring.boot.admin.client.instance.name=framework-back
spring.boot.admin.client.instance.management-base-url=http://197.200.1.81:9981
spring.boot.admin.client.instance.service-base-url=http://197.200.1.81:9981
management.endpoints.web.exposure.include=*
management.health.elasticsearch.enabled=false

logging.file.name=/data/apps/ije-eacct/logs/client.log
logging.pattern.file=-%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx

address.frontend=http://eleceas.iljin.co.kr
address.backend=http://eleceas.iljin.co.kr:19500
spring.profiles.include=oauth

etax.smartbill.url=http://197.200.1.19:10002
etax.smartbill.id=ije12486
etax.smartbill.pwd=a1234567